(ns lorembarnak.swears-db)

(def swears [["tabarnak" "tabarnouche" "tabarouette" "taboire" "tabarslaque"]
             ["câlisse" "câlique" "câline" "câline de bine" "câliboire"]
             ["crisse" "christie" "crime"]
             ["ostie" "astie" "estique" "ostifie" "esprit"]
             ["ciboire" "saint-ciboire"]
             ["torrieux"]
             ["cimonaque" "saint-cimonaque"]
             ["baptême" "batince"]
             ["bâtard"]
             ["calvaire" "calvince"]
             ["mosus"]
             ["maudit" "mautadit" "maudine"]
             ["sacrament"]
             ["viarge" "sainte-viarge" "bout d'viarge"]
             ["cibouleau"]
             ["sacréfice"]
             ["cibole" "cibolac"]
             ["enfant d'chienne"]
             ["verrat"]
             ["marde" "maudite marde"]
             ["boswell"]
             ["sacristi" "sapristi"]
             ["jésus de plâtre" "jérusalem"]
             ["torvisse"]
             ["patente à gosse"]
             ["viande à chien"]
             ["bout d'crisse"]
             ["cul"]
             ["jésus marie joseph"]
             ["charrue"]
             ["charogne"]
             ["gériboire"]
             ["sac à papier"]
             ["sainte peanut du ciel" "saint-chrème" "sainte-jument"]])
